### PR TITLE
gitignore (copied from grawdiahub)

### PR DESCRIPTION
**Pull request by goteusz-maszyk**

### CODE REVIEW

**Review by Sanielia — COMMENTED** [review]
Are you @tapczanek1321 that you are adding it or what?

**Review by Sanielia — CHANGES_REQUESTED** [review]
This is shit

**Review by Norbiros — CHANGES_REQUESTED** [review]
This isn't a python project <3

**Review by Sanielia — APPROVED** [review]
LGTM

**Review by Norbiros — APPROVED** [review]

**Review by Sanielia — APPROVED** [review]

**Pull request merged**
